// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKT_qQxE0xzPY5iFCQNf7WfN2XX_kEXI',
    appId: '1:30127769540:web:76e7bf68bdc35118c6c691',
    messagingSenderId: '30127769540',
    projectId: 'spotify-1d694',
    authDomain: 'spotify-1d694.firebaseapp.com',
    storageBucket: 'spotify-1d694.firebasestorage.app',
    measurementId: 'G-7SZLP6GQ08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5ebCE-fKwz2nP_4gX-_v_XGwSooQZCI',
    appId: '1:30127769540:android:80831510ba5616fac6c691',
    messagingSenderId: '30127769540',
    projectId: 'spotify-1d694',
    storageBucket: 'spotify-1d694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwv5mUAaPC8_l1ZQ2kcyP2Y5Msg3AqZg',
    appId: '1:30127769540:ios:36408e42adc4ca10c6c691',
    messagingSenderId: '30127769540',
    projectId: 'spotify-1d694',
    storageBucket: 'spotify-1d694.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwv5mUAaPC8_l1ZQ2kcyP2Y5Msg3AqZg',
    appId: '1:30127769540:ios:36408e42adc4ca10c6c691',
    messagingSenderId: '30127769540',
    projectId: 'spotify-1d694',
    storageBucket: 'spotify-1d694.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXKT_qQxE0xzPY5iFCQNf7WfN2XX_kEXI',
    appId: '1:30127769540:web:efe1beddc6afa3ebc6c691',
    messagingSenderId: '30127769540',
    projectId: 'spotify-1d694',
    authDomain: 'spotify-1d694.firebaseapp.com',
    storageBucket: 'spotify-1d694.firebasestorage.app',
    measurementId: 'G-3K66YHH9HP',
  );
}
